Repository OCA/l10n-belgium, pull requests merged in 2021-04, with the labels that each got.

#106 [13.0] update dotfiles
  .copier-answers.yml
  .flake8
  .github/workflows/pre-commit.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  l10n_be_mis_reports/__manifest__.py
  l10n_be_partner_identification/__manifest__.py
  l10n_be_partner_kbo_bce/models/res_partner.py
  oca_dependencies.txt
Labels: bot is merging ⏳

#96 [13.0][MIG] account bank statement import coda
  account_bank_statement_import_coda/README.rst
  account_bank_statement_import_coda/__init__.py
  account_bank_statement_import_coda/__manifest__.py
  account_bank_statement_import_coda/i18n/account_bank_statement_import_coda.pot
  account_bank_statement_import_coda/i18n/ca_ES.po
  account_bank_statement_import_coda/i18n/de.po
  account_bank_statement_import_coda/i18n/fi.po
  account_bank_statement_import_coda/i18n/fr.po
  account_bank_statement_import_coda/i18n/nl_NL.po
  account_bank_statement_import_coda/models/__init__.py
  account_bank_statement_import_coda/models/account_journal.py
  account_bank_statement_import_coda/readme/CONTRIBUTORS.rst
  account_bank_statement_import_coda/readme/DESCRIPTION.rst
  account_bank_statement_import_coda/readme/INSTALL.rst
  account_bank_statement_import_coda/static/description/icon.png
  account_bank_statement_import_coda/static/description/index.html
  account_bank_statement_import_coda/test_coda_file/Ontvangen_CODA.2012-01-11-18.59.15.txt
  account_bank_statement_import_coda/tests/__init__.py
  account_bank_statement_import_coda/tests/test_import_bank_statement.py
  account_bank_statement_import_coda/wizard/__init__.py
  account_bank_statement_import_coda/wizard/account_bank_statement_import_coda.py
  account_bank_statement_import_coda/wizard/account_bank_statement_import_coda_view.xml
  setup/account_bank_statement_import_coda/odoo/addons/account_bank_statement_import_coda
  setup/account_bank_statement_import_coda/setup.py
Labels: approved, bot is merging ⏳

#107 [14.0][FIX] companyweb_base: don't import tests
  companyweb_base/__init__.py
Labels: 14.0
