Repository OCA/l10n-belgium, pull requests merged in 2022-01, with the labels that each got.

#120 [14.0][FIX] companyweb_base: fix test - vcrpy integration
  companyweb_base/tests/test_api_cweb.py
Labels: bot is merging ⏳

#114 [14.0][MIG] l10n_be_mis_reports: Migration to 14.0
  l10n_be_mis_reports/README.rst
  l10n_be_mis_reports/__init__.py
  l10n_be_mis_reports/__manifest__.py
  l10n_be_mis_reports/data/mis_report_bs.xml
  l10n_be_mis_reports/data/mis_report_pl.xml
  l10n_be_mis_reports/data/mis_report_styles.xml
  l10n_be_mis_reports/i18n/fr.po
  l10n_be_mis_reports/i18n/l10n_be_mis_reports.pot
  l10n_be_mis_reports/i18n/nl.po
  l10n_be_mis_reports/readme/CONFIGURE.rst
  l10n_be_mis_reports/readme/CONTRIBUTORS.rst
  l10n_be_mis_reports/readme/DESCRIPTION.rst
  l10n_be_mis_reports/readme/INSTALL.rst
  l10n_be_mis_reports/readme/USAGE.rst
  l10n_be_mis_reports/static/description/icon.png
  l10n_be_mis_reports/static/description/index.html
  setup/l10n_be_mis_reports/odoo/addons/l10n_be_mis_reports
  setup/l10n_be_mis_reports/setup.py
Labels: approved, bot is merging ⏳, blocked by dependency

#122 [13.0] ci: test with GitHub actions
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .t2d.yml
Labels: 13.0

#113 [14.0][ADD] companyweb payment info xbo
  companyweb_base/models/res_partner.py
  companyweb_base/security/ir.model.access.csv
  companyweb_base/wizards/__init__.py
  companyweb_base/wizards/credential_wizard.xml
  companyweb_base/wizards/credential_wizard_abstract.py
  companyweb_base/wizards/credential_wizard_base.py
  companyweb_payment_info/README.rst
  companyweb_payment_info/__init__.py
  companyweb_payment_info/__manifest__.py
  companyweb_payment_info/i18n/companyweb_payment_info.pot
  companyweb_payment_info/i18n/fr.po
  companyweb_payment_info/i18n/nl.po
  companyweb_payment_info/readme/CONTRIBUTORS.rst
  companyweb_payment_info/readme/CREDITS.rst
  companyweb_payment_info/readme/DESCRIPTION.rst
  companyweb_payment_info/readme/INSTALL.rst
  companyweb_payment_info/readme/USAGE.rst
  companyweb_payment_info/security/ir.model.access.csv
  companyweb_payment_info/security/security.xml
  companyweb_payment_info/static/description/icon.png
  companyweb_payment_info/static/description/index.html
  companyweb_payment_info/static/img/logo-en.png
  companyweb_payment_info/static/img/logo-en.resized.png
  companyweb_payment_info/tests/__init__.py
  companyweb_payment_info/tests/cassettes/TestUpload.test_upload_payment.yaml
  companyweb_payment_info/tests/test_cweb_upload.py
  companyweb_payment_info/wizards/__init__.py
  companyweb_payment_info/wizards/credential_wizard_payment.py
  companyweb_payment_info/wizards/payment_info_wizard.py
  companyweb_payment_info/wizards/payment_info_wizard.xml
  setup/companyweb_payment_info/odoo/addons/companyweb_payment_info
  setup/companyweb_payment_info/setup.py
Labels: bot is merging ⏳

#109 [14.0][MIG] 10n_be_partner_kbo_bce
  l10n_be_partner_kbo_bce/README.rst
  l10n_be_partner_kbo_bce/__init__.py
  l10n_be_partner_kbo_bce/__manifest__.py
  l10n_be_partner_kbo_bce/data/res_partner_id_category.xml
  l10n_be_partner_kbo_bce/demo/res_partner.xml
  l10n_be_partner_kbo_bce/i18n/fr.po
  l10n_be_partner_kbo_bce/i18n/l10n_be_partner_kbo_bce.pot
  l10n_be_partner_kbo_bce/i18n/nl.po
  l10n_be_partner_kbo_bce/models/__init__.py
  l10n_be_partner_kbo_bce/models/res_partner.py
  l10n_be_partner_kbo_bce/models/res_partner_id_category.py
  l10n_be_partner_kbo_bce/readme/CONTRIBUTORS.rst
  l10n_be_partner_kbo_bce/readme/DESCRIPTION.rst
  l10n_be_partner_kbo_bce/readme/INSTALL.rst
  l10n_be_partner_kbo_bce/static/description/icon.png
  l10n_be_partner_kbo_bce/static/description/index.html
  l10n_be_partner_kbo_bce/tests/__init__.py
  l10n_be_partner_kbo_bce/tests/test_l10n_be_partner_kbo_bce.py
  l10n_be_partner_kbo_bce/views/res_partner.xml
  setup/l10n_be_partner_kbo_bce/odoo/addons/l10n_be_partner_kbo_bce
  setup/l10n_be_partner_kbo_bce/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#128 [12.0] fix partner vat listing file extension
  l10n_be_vat_reports/readme/CONTRIBUTORS.rst
  l10n_be_vat_reports/wizard/l10n_be_partner_vat_listing.py
  l10n_be_vat_reports/wizard/l10n_be_partner_vat_listing.xml
Labels: approved, bot is merging ⏳
