Repository OCA/l10n-belgium, pull requests merged in 2024-01, with the labels that each got.

#198 [16.0][MIG] l10n_be_mis_reports_xml
  l10n_be_mis_reports_xml/README.rst
  l10n_be_mis_reports_xml/__init__.py
  l10n_be_mis_reports_xml/__manifest__.py
  l10n_be_mis_reports_xml/data/data.xml
  l10n_be_mis_reports_xml/i18n/l10n_be_mis_reports_xml.pot
  l10n_be_mis_reports_xml/models/__init__.py
  l10n_be_mis_reports_xml/models/mis_report_instance.py
  l10n_be_mis_reports_xml/readme/CONTRIBUTORS.rst
  l10n_be_mis_reports_xml/readme/DESCRIPTION.rst
  l10n_be_mis_reports_xml/readme/USAGE.rst
  l10n_be_mis_reports_xml/reports/be_vat_declaration.xml
  l10n_be_mis_reports_xml/security/ir.model.access.csv
  l10n_be_mis_reports_xml/static/description/icon.png
  l10n_be_mis_reports_xml/static/description/index.html
  l10n_be_mis_reports_xml/tests/__init__.py
  l10n_be_mis_reports_xml/tests/test_l10n_be_mis_reports_xml.py
  l10n_be_mis_reports_xml/views/mis_report_instance.xml
  l10n_be_mis_reports_xml/wizards/__init__.py
  l10n_be_mis_reports_xml/wizards/be_vat_declaration_wizard.py
  l10n_be_mis_reports_xml/wizards/be_vat_declaration_wizard.xml
  setup/l10n_be_mis_reports_xml/odoo/addons/l10n_be_mis_reports_xml
  setup/l10n_be_mis_reports_xml/setup.py
Labels: approved, bot is merging ⏳

#183 [16.0] [MIG] l10n_be_partner_identification
  l10n_be_partner_identification/README.rst
  l10n_be_partner_identification/__init__.py
  l10n_be_partner_identification/__manifest__.py
  l10n_be_partner_identification/data/l10n_be_partner_identification.xml
  l10n_be_partner_identification/i18n/l10n_be_partner_identification.pot
  l10n_be_partner_identification/models/__init__.py
  l10n_be_partner_identification/models/res_partner_id_category.py
  l10n_be_partner_identification/static/description/icon.png
  l10n_be_partner_identification/tests/__init__.py
  l10n_be_partner_identification/tests/test_l10n_be_partner_identification.py
  setup/l10n_be_partner_identification/odoo/addons/l10n_be_partner_identification
  setup/l10n_be_partner_identification/setup.py
Labels: approved, bot is merging ⏳, no stale

#140 [14.0][FIX] account_statement_import_coda: note should only contain info of the current move
  account_statement_import_coda/wizard/account_statement_import_coda.py
Labels: approved, ready to merge, bot is merging ⏳
