Repository OCA/l10n-belgium, pull requests merged in 2025-04, with the labels that each got.

#224 [17.0][MIG] l10n_be_mis_reports
  l10n_be_mis_reports/README.rst
  l10n_be_mis_reports/__init__.py
  l10n_be_mis_reports/__manifest__.py
  l10n_be_mis_reports/data/mis_report_bs_deprecated.xml
  l10n_be_mis_reports/data/mis_report_bs_m01-f.xml
  l10n_be_mis_reports/data/mis_report_bs_m02-f.xml
  l10n_be_mis_reports/data/mis_report_bs_m04-f.xml
  l10n_be_mis_reports/data/mis_report_bs_m05-f.xml
  l10n_be_mis_reports/data/mis_report_bs_m07-f.xml
  l10n_be_mis_reports/data/mis_report_bs_m08-f.xml
  l10n_be_mis_reports/data/mis_report_bs_m81-f.xml
  l10n_be_mis_reports/data/mis_report_bs_m82-f.xml
  l10n_be_mis_reports/data/mis_report_bs_m87-f.xml
  l10n_be_mis_reports/data/mis_report_pl_deprecated.xml
  l10n_be_mis_reports/data/mis_report_pl_m01-f.xml
  l10n_be_mis_reports/data/mis_report_pl_m02-f.xml
  l10n_be_mis_reports/data/mis_report_pl_m04-f.xml
  l10n_be_mis_reports/data/mis_report_pl_m05-f.xml
  l10n_be_mis_reports/data/mis_report_pl_m07-f.xml
  l10n_be_mis_reports/data/mis_report_pl_m08-f.xml
  l10n_be_mis_reports/data/mis_report_pl_m81-f.xml
  l10n_be_mis_reports/data/mis_report_pl_m82-f.xml
  l10n_be_mis_reports/data/mis_report_pl_m87-f.xml
  l10n_be_mis_reports/data/mis_report_styles.xml
  l10n_be_mis_reports/data/mis_report_vat.xml
  l10n_be_mis_reports/i18n/de.po
  l10n_be_mis_reports/i18n/es.po
  l10n_be_mis_reports/i18n/fr.po
  l10n_be_mis_reports/i18n/l10n_be_mis_reports.pot
  l10n_be_mis_reports/i18n/nl.po
  l10n_be_mis_reports/pyproject.toml
  l10n_be_mis_reports/readme/CONFIGURE.md
  l10n_be_mis_reports/readme/CONTRIBUTORS.md
  l10n_be_mis_reports/readme/DESCRIPTION.md
  l10n_be_mis_reports/readme/INSTALL.md
  l10n_be_mis_reports/readme/USAGE.md
  l10n_be_mis_reports/script/README.rst
  l10n_be_mis_reports/script/calc/22_19_m01-f.json
  l10n_be_mis_reports/script/calc/22_19_m02-f.json
  l10n_be_mis_reports/script/calc/22_19_m04-f.json
  l10n_be_mis_reports/script/calc/22_19_m05-f.json
  l10n_be_mis_reports/script/calc/22_19_m07-f.json
  l10n_be_mis_reports/script/calc/22_19_m08-f.json
  l10n_be_mis_reports/script/calc/22_19_m81-f.json
  l10n_be_mis_reports/script/calc/22_19_m82-f.json
  l10n_be_mis_reports/script/calc/22_19_m87-f.json
  l10n_be_mis_reports/script/correct_xml.py
  l10n_be_mis_reports/script/data/m01-f.json
  l10n_be_mis_reports/script/data/m02-f.json
  l10n_be_mis_reports/script/data/m04-f.json
  l10n_be_mis_reports/script/data/m05-f.json
  l10n_be_mis_reports/script/data/m07-f.json
  l10n_be_mis_reports/script/data/m08-f.json
  l10n_be_mis_reports/script/data/m81-f.json
  l10n_be_mis_reports/script/data/m82-f.json
  l10n_be_mis_reports/script/data/m87-f.json
  l10n_be_mis_reports/script/generate_xml.py
  l10n_be_mis_reports/script/generate_xml.sh
  l10n_be_mis_reports/static/description/icon.png
  l10n_be_mis_reports/static/description/index.html
Labels: bot is merging ⏳

#247 [16.0][FIX] l10n_be_intrastat_product: Menu compatibility with other intrastat
  l10n_be_intrastat_product/views/intrastat_product_views.xml
Labels: approved, bot is merging ⏳

#225 [MIG] l10n_be_intrastat_product: Migration to 17.0
  l10n_be_intrastat_product/README.rst
  l10n_be_intrastat_product/__init__.py
  l10n_be_intrastat_product/__manifest__.py
  l10n_be_intrastat_product/data/intrastat_region.xml
  l10n_be_intrastat_product/doc/intrastat_manual_basis_en.pdf
  l10n_be_intrastat_product/i18n/l10n_be_intrastat_product.pot
  l10n_be_intrastat_product/models/__init__.py
  l10n_be_intrastat_product/models/intrastat_product_declaration.py
  l10n_be_intrastat_product/pyproject.toml
  l10n_be_intrastat_product/readme/CONFIGURE.md
  l10n_be_intrastat_product/readme/CONTRIBUTORS.md
  l10n_be_intrastat_product/readme/DESCRIPTION.md
  l10n_be_intrastat_product/readme/HISTORY.md
  l10n_be_intrastat_product/readme/INSTALL.md
  l10n_be_intrastat_product/readme/ROADMAP.md
  l10n_be_intrastat_product/security/intrastat_security.xml
  l10n_be_intrastat_product/static/data/2022_de_intrastat_codes.csv
  l10n_be_intrastat_product/static/data/2022_en_intrastat_codes.csv
  l10n_be_intrastat_product/static/data/2022_fr_intrastat_codes.csv
  l10n_be_intrastat_product/static/data/2022_nl_intrastat_codes.csv
  l10n_be_intrastat_product/static/data/ex19e.xsd
  l10n_be_intrastat_product/static/data/ex19s.xsd
  l10n_be_intrastat_product/static/data/intrastat_x_e.xsd
  l10n_be_intrastat_product/static/data/intrastat_x_s.xsd
  l10n_be_intrastat_product/static/description/icon.png
  l10n_be_intrastat_product/static/description/index.html
  l10n_be_intrastat_product/tests/__init__.py
  l10n_be_intrastat_product/tests/test_intrastat_be.py
  l10n_be_intrastat_product/views/account_move_views.xml
  l10n_be_intrastat_product/views/intrastat_product_views.xml
Labels: approved, bot is merging ⏳, stale
